### ISSUE TITLE
List for tag description?

### ISSUE THREAD

**Issue by ChiyoDragon** [thegeeklab/ansible-doctor#739] opened 2024-07-16 14:43 UTC
Hi,

I'm encountering an issue with line breaks in the tag descriptions when using the ansible-doctor template. The template looks like this:

```
{% set tag = role.tag | default({}) %}
{% if tag %}
## Discovered Tags
{% for key, item in tag.items() if tag is mapping %}
{% set is_desc = item.description is defined and item.description | safe_join(" ") | striptags %}

**_{{ key }}_**{{ "\\" if is_desc else "" }}
{% if is_desc %}
{{ item.description | safe_join(" ") | striptags | replace("1. ", "\n1. ") | replace("2. ", "\n2. ") | replace("3. ", "\n3. ") | replace("4. ", "\n4. ") | replace("5. ", "\n5. ") | replace("6. ", "\n6. ") | replace("7. ", "\n7. ") | replace("8. ", "\n8. ") | replace("9. ", "\n9. ") | replace("0. ", "\n0. ") }}
{% endif %}
{% endfor %}
{% endif %}
```

While the template looks good, it results in unwanted line breaks and numbers at the end of the lines, making the output look like this:
![tags](https://github.com/user-attachments/assets/fcded707-0b7a-4e17-a560-eeb66dc244df)

```

## Discovered Tags

**_install-apache_**\
The following tasks are part of the Apache installation and configuration process in an Ansible role. 
1. **FILE | create {{ apache_symlink_src }}**: This task creates a directory for the Apache symlink source. 
2. **FILE | create {{ apache_www_symlink_src }}**: This task creates a directory for the Apache www symlink source. 
3. **APT | install apache2 and needed packages**: This task installs Apache2 and required packages using the apt package manager. 
4. **Enable apache2 modules**: This task enables specified Apache2 modules. 
5. **TEMPLATE | update vhost**: This task updates the virtual host configuration. 
6. **TEMPLATE | update SSL config**: This task updates the SSL configuration. 
7. **TEMPLATE | update mpm_event config**: This task updates the mpm_event configuration. 
8. **TEMPLATE | update status config**: This task updates the status module configuration. 
9. **TEMPLATE | update security config**: This task updates the security configuration. 1
0. **TEMPLATE | update ports config**: This task updates the ports configuration. 1
1. **TEMPLATE | update apache2 config**: This task updates the main Apache2 configuration file. 1
2. **APT | install mod_security packages**: This task installs ModSecurity packages. 1
3. **TEMPLATE | deploy ModSecurity Config**: This task deploys the ModSecurity configuration. 1
4. **FILE | enable ModSecurity Config**: This task enables the ModSecurity configuration. 1
5. **FILE | removing default vhost**: This task removes the default virtual host configuration. 1
6. **STAT | check if /etc/apache2 exists**: This task checks if the /etc/apache2 directory exists. 1
7. **FILE | create temporary directory /tmp/ansible-apache-tmp for saving what is inside of /etc/apache2**: This task creates a temporary directory to save the contents of /etc/apache
2. 1
```

I've tried different approaches to remove the unwanted numbers at the end of the lines, but I haven't found a solution yet.

Additionally, using the original template (which we are not currently using) didn't work at all for handling these descriptions properly.

Could you please advise on how to correctly handle the line breaks and avoid the extra numbers at the end of the descriptions?

Thank you!

**Comment by xoxys** [comment] 2024-07-18 08:31
Hi can you please provide a reproducible example? Especially the annotated tasks file.

**Comment by xoxys** [comment] 2024-08-15 08:39
Closing due to missing feedback.

**Closed by xoxys** 2024-08-15 08:39 UTC
