### ISSUE TITLE
Support Ansible collections

### ISSUE THREAD

**Issue by HauserV** [thegeeklab/ansible-doctor#523] opened 2023-07-11 10:13 UTC
I'm trying to use ansible-doctor with an [Ansible collection](https://docs.ansible.com/ansible/latest/dev_guide/developing_collections_structure.html#collection-directories-and-files) repository and I would like to define the configuration once in the root directory (i.e., as a sibling to the `roles` directory) and have it recurse over all roles inside. For example, the structure looks like so 

```
.:
roles/
.ansibledoctor.yml

./roles:
roleA/
roleB/

./roles/roleA:
tasks/

./roles/roleA/tasks:
main.yml

./roles/roleB:
tasks/

./roles/roleB/tasks:
main.yml
```

In the MWE, the `.ansibledoctor.yml` contains

```yaml
---
base_dir: roles
```

However I can't get ansible-doctor to use it...

1. It finds the config but not the roles when called without arguments (the automatic role detection doesn't traverse into the `roles` directory).
    ```
    $ ansible-doctor -v
    [INFO] Using config file: C:\Users\hauserv\git\test\.ansibledoctor.yml
    [CRITICAL] No Ansible role detected
    ```
2. It finds neither when called with `--recursive` (it either ignores the folder-based config altogether or perhaps traverses into the `roles` directory, fails to find a `.ansibledoctor.yml` and uses a global config)
    ```
    $ ansible-doctor -vr
    [INFO] Using config file: C:\Users\hauserv\AppData\Local\ansible-doctor\ansible-doctor\config.yml
    [CRITICAL] No Ansible role detected
    ```
3. It finds the roles but not the config when both `base_dir` is passed in as a positional argument in addition to the `--config` (it claims to use config files such as `roles/roleA/.ansibledoctor.yml` which don't exist).
    ```
    $ ansible-doctor -vr -c .ansibledoctor.yml roles
    [INFO] Using config file: C:\Users\hauserv\git\test\roles\roleA\.ansibledoctor.yml
    [INFO] Ansible role detected: roleA
    [INFO] Finding annotations for: @meta
    [INFO] Finding annotations for: @todo
    [INFO] Finding annotations for: @var
    [INFO] Finding annotations for: @example
    [INFO] Finding annotations for: @tag
    [INFO] Using template dir: C:\Python39\Lib\site-packages\ansibledoctor\templates\readme
    [INFO] Using output dir: C:\Users\hauserv\git\test\roles\roleA
    [INFO] Writing to: C:\Users\hauserv\git\test\roles\roleA\README.md
    [INFO] Using config file: C:\Users\hauserv\git\test\roles\roleB\.ansibledoctor.yml
    [INFO] Ansible role detected: roleB
    [INFO] Finding annotations for: @meta
    [INFO] Finding annotations for: @todo
    [INFO] Finding annotations for: @var
    [INFO] Finding annotations for: @example
    [INFO] Finding annotations for: @tag
    [INFO] Using template dir: C:\Python39\Lib\site-packages\ansibledoctor\templates\readme
    [INFO] Using output dir: C:\Users\hauserv\git\test\roles\roleB
    [INFO] Writing to: C:\Users\hauserv\git\test\roles\roleB\README.md
    ```

**Comment by xoxys** [comment] 2023-08-09 06:56
What works is using an absolute path to the config file `ansible-doctor -c $(pwd)/.ansibledoctor.yml -r roles/ -f`.

**Comment by xoxys** [comment] 2023-08-09 07:05
I'm unsure what's the expected behavior would be. Should the config file lookup always use the execution directory as base dir? Even if `--recursive` is used?

**Comment by xoxys** [comment] 2023-09-18 14:50
Closing due to missing feedback.

**Closed by xoxys** 2023-09-18 14:50 UTC
Labels: enhancement
